<?php
use App\Helpers\ViewHelper;
$page_title ='Two-Factor Authentication';
ViewHelper::loadHeader($page_title);
?>
<h1>Two-Factor Authentication</h1>
<p>Please enter the 6-digit code generated by your application to confirm your sign in.</p>
<form method="POST"
//TODO: add php file to action
action="">

    <input type="text" name="code" id="code" required>

    <button type="submit">Verify</button>
    <button type="submit">Resend Code</button>

</form>
<?php
ViewHelper::loadJsScripts();
ViewHelper::loadFooter();
