<?php
use App\Helpers\ViewHelper;
$page_title = 'Two-Factor Authentication';
ViewHelper::loadHeader($page_title);
?>

<div class="twofactor-container">
  <a href="#" class="close-btn">X</a>

  <h1>Two-Factor Authentication</h1>
  <p>Please enter the 6-digit code generated by your application to confirm your sign in.</p>

  <form method="POST" action="">
    <input type="text" name="code" id="code" maxlength="6" placeholder="XXXXXX" required>

    <div>
      <button type="submit" class="verify">Verify</button>
      <button type="button" class="resend">Resend Code</button>
    </div>
  </form>
</div>

<?php
ViewHelper::loadJsScripts();
ViewHelper::loadFooter();
?>
