<?php

use App\Helpers\ViewHelper;

$page_title = 'Login page';
ViewHelper::loadHeader($page_title, false);
?>

<div class="login-container">


    <div class="left-panel">
        <h1>VKC</h1>
        <h4>[If VKC is short for something, update with the full company name]</h4>
        <h2>[Insert Subtitle Here (a short hook/summary of the company)]</h2>

        <div class="description-box">
            <p>[INSERT Description - Summary of who/what/where is the company...]</p>
            <p>BLALALALALALALALALALALALALALLALALALALALA</p>
            <p>LALALALALALALALALALA</p>
            <p>Socials:<br>[insert social media links here]</p>
        </div>
    </div>




    <div class="form-panel">

        <div class="center-logo">
            <div class="logo-circle">VKC</div>
        </div>
        <form method="POST" action="">
            <label for="email">Email Address</label>
            <input type="text" name="email" id="email" required>
            <a href="#">Forgot Email?</a>
            <br>
            <br>
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required>
            <a href="#">Forgot Password?</a>

            <div class="button-row">
                <button type="submit" class="signup-btn">Sign Up</button>
                <button type="submit" class="signin-btn">Sign In</button>
            </div>
        </form>
    </div>




</div>
<!-- FORGOT PASSWORD POPUP -->
<div id="forgotPasswordModal" class="forgot-modal-overlay">
    <div class="forgot-modal-box">
        <span class="close-forgot">X</span>

        <h2>Forgot Password</h2>
        <p>Please enter the 6-digit code generated by your email to confirm your account.</p>

        <label>Email Address</label>
        <input type="email" placeholder="example@email.com">

        <label>Verification code:</label>
        <input type="text" maxlength="6" placeholder="0 0 0 0 0 0">

        <div class="forgot-btn-row">
            <button class="forgot-send">Send Email</button>
            <button type="button" class="forgot-change"onclick="openNewPasswordModal()">Change Password</button>
        </div>
    </div>
</div>
<!--  New Password MODAL -->
<div id="new-password-modal" class="forgot-modal-overlay">
    <div class="forgot-modal-box">

        <!-- Use same close button class -->
        <span class="close-forgot" onclick="closeNewPasswordModal()">X</span>

        <h2>New Password</h2>
        <p>Please enter a new password.</p>

        <form id="newPasswordForm">

            <label>New Password:</label>
            <input type="password" placeholder="Enter new password" required>

            <label>Confirm New Password:</label>
            <input type="password" placeholder="Confirm new password" required>

            <div class="forgot-btn-row">
                <!-- Use same button styles -->
                <button type="button" class="forgot-send" onclick="submitNewPassword()">Send</button>
                <button type="button" class="forgot-change" onclick="closeNewPasswordModal()">Cancel</button>
            </div>
        </form>

    </div>
</div>
<!-- FORGOT EMAIL MODAL -->
<div id="forgotEmailModal" class="forgot-modal-overlay">
    <div class="forgot-modal-box">

        <span class="close-forgot" onclick="closeForgotEmailModal()">X</span>

        <h2>Forgot Email</h2>
        <p>Please enter your name and mobile number.<br>
        If there is an account with information you input here, you will receive a SMS message to regain access to your account.</p>

        <form id="forgotEmailForm">
            <label>First Name:</label>
            <input type="text" placeholder="Enter first name" required>

            <label>Last Name:</label>
            <input type="text" placeholder="Enter last name" required>

            <label>Mobile Number:</label>
            <input type="text" placeholder="000-000-0000" required>

            <div class="forgot-btn-row">
                <button type="button" class="forgot-change" onclick="closeForgotEmailModal()">Cancel</button>
                <button type="button" class="forgot-send" onclick="sendForgotEmail()">Send Message</button>
            </div>
        </form>

    </div>
</div>
<!-- New Email MODAL -->
<div id="new-email-modal" class="forgot-modal-overlay">
    <div class="forgot-modal-box">

        <!-- Use same close button class -->
        <span class="close-forgot" onclick="closeNewEmailModal()">X</span>

        <h2>New Email</h2>
        <p>Please enter a new email.</p>

        <form id="newEmailForm">

            <label>New Email:</label>
            <input type="password" placeholder="Enter new email" required>

            <label>Confirm New Email:</label>
            <input type="password" placeholder="Confirm new email" required>

            <div class="forgot-btn-row">
                <!-- Use same button styles -->
                <button type="button" class="forgot-send" onclick="submitNewEmail()">Send</button>
                <button type="button" class="forgot-change" onclick="closeNewEmailModal()">Cancel</button>
            </div>
        </form>

    </div>
</div>
<!-- 2-factor MODAL -->
<div id="two-factor-modal" class="forgot-modal-overlay">
    <div class="forgot-modal-box">

        <!-- Use same close button class -->
        <span class="close-forgot" onclick="">X</span>

        <h2>Two Factor Authentification</h2>
        <p>Please enter the 6-digit code generated by your application to confirm your login.</p>

        <form id="newEmailForm">


            <input type="password" placeholder="000000" required>



            <div class="forgot-btn-row">
                <!-- Use same button styles -->
                <button type="button" class="forgot-send" onclick="">Resend Code</button>
                <button type="button" class="forgot-change" onclick="">Verify</button>
            </div>
        </form>

    </div>
</div>
<!-- FOOTER BAR BUT only for the login page so idk if we should have a separate file/footer for it -->
<div class="lang-switch">
    <div class="left">
        <a href="">EN</a> - <a href="">FR</a>
    </div>
    <div class="center">
        # of registered employees, join the team, register today.
    </div>
    <div class="right">
        <span id="datetime-display"></span>
    </div>
</div>

<?php
ViewHelper::loadJsScripts();
ViewHelper::loadFooter();
?>
