<?php

use App\Helpers\ViewHelper;
var_dump($data);
//* DYNAMIC POPUPS
$show2fa_login = $data['show2fa_login'] ?? false;
$show_forgot_password = $render['show_forgot_password'] ?? false;
$show_forgot_password_2fa = $render['show_forgot_password_2fa'] ?? false;
$show_new_password = $render['show_new_password'] ?? false;

$show_forgot_email = $render['show_forgot_email'] ?? false;
$show_forgot_email_2fa = $render['show_forgot_email_2fa'] ?? false;
$show_new_email = $render['show_new_email'] ?? false;
echo $show2fa_login;
$page_title ='Login page';
ViewHelper::loadHeader($page_title,false);

?>
<div><?= $show2fa_login ?></div>
<div class="login-container">

<?= App\Helpers\FlashMessage::render() ?>
    <div class="left-panel">
        <h1>VKC</h1>
        <h4>[If VKC is short for something, update with the full company name]</h4>
        <h2>[Insert Subtitle Here (a short hook/summary of the company)]</h2>

        <div class="description-box">
            <p>[INSERT Description - Summary of who/what/where is the company...]</p>
            <p>BLALALALALALALALALALALALALALLALALALALALA</p>
            <p>LALALALALALALALALALA</p>
            <p>Socials:<br>[insert social media links here]</p>
        </div>
    </div>

<<<<<<< HEAD
<?= App\Helpers\FlashMessage::render() ?>


=======
>>>>>>> ce6db419c33c5ef13caef49eb8242292f2e05051
    <div class="form-panel">

        <div class="center-logo">
            <div class="logo-circle">VKC</div>
        </div>
        <?= App\Helpers\FlashMessage::render() ?>
        <form method="POST" action="<?= APP_BASE_URL ?>/login">
            <label for="email">Email Address</label>
            <input type="text" name="email" id="email" required style="color:white;">
            <a href="#">Forgot Email?</a>
            <br>
            <br>
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required style="color:white;">
            <a href="#">Forgot Password?</a>

            <div class="button-row">
                <a class='btn btn-success' href="<?= APP_BASE_URL ?>/register">Sign in</a>
                <button type="submit" class="signin-btn">Sign In</button>
            </div>
        </form>
    </div>

</div>
<!-- FORGOT PASSWORD POPUP -->
<div id="forgotPasswordModal" class="forgot-modal-overlay">
    <div class="forgot-modal-box">
        <span class="close-forgot">X</span>

        <h2>Forgot Password</h2>
        <p>Please enter the 6-digit code generated by your email to confirm your account.</p>

        <label>Email Address</label>
        <input type="email" placeholder="example@email.com">

        <label>Verification code:</label>
        <input type="text" maxlength="6" placeholder="0 0 0 0 0 0">

        <div class="forgot-btn-row">
            <button class="forgot-send">Send Email</button>
            <button type="button" class="forgot-change"onclick="openNewPasswordModal()">Change Password</button>
        </div>
    </div>
</div>
<!--  New Password MODAL -->
<div id="new-password-modal" class="forgot-modal-overlay">
    <div class="forgot-modal-box">

        <!-- Use same close button class -->
        <span class="close-forgot" onclick="closeNewPasswordModal()">X</span>

        <h2>New Password</h2>
        <p>Please enter a new password.</p>

        <form id="newPasswordForm">

            <label>New Password:</label>
            <input type="password" placeholder="Enter new password" required>

            <label>Confirm New Password:</label>
            <input type="password" placeholder="Confirm new password" required>

            <div class="forgot-btn-row">
                <!-- Use same button styles -->
                <button type="button" class="forgot-send" onclick="submitNewPassword()">Send</button>
                <button type="button" class="forgot-change" onclick="closeNewPasswordModal()">Cancel</button>
            </div>
        </form>

    </div>
</div>
<!-- FORGOT EMAIL MODAL -->
<div id="forgotEmailModal" class="forgot-modal-overlay">
    <div class="forgot-modal-box">

        <span class="close-forgot" onclick="closeForgotEmailModal()">X</span>

        <h2>Forgot Email</h2>
        <p>Please enter your name and mobile number.<br>
        If there is an account with information you input here, you will receive a SMS message to regain access to your account.</p>

        <form id="forgotEmailForm">
            <label>First Name:</label>
            <input type="text" placeholder="Enter first name" required>

            <label>Last Name:</label>
            <input type="text" placeholder="Enter last name" required>

            <label>Mobile Number:</label>
            <input type="text" placeholder="000-000-0000" required>

            <div class="forgot-btn-row">
                <button type="button" class="forgot-change" onclick="closeForgotEmailModal()">Cancel</button>
                <button type="button" class="forgot-send" onclick="sendForgotEmail()">Send Message</button>
            </div>
        </form>

    </div>
</div>
<!-- New Email MODAL -->
<div id="new-email-modal" class="forgot-modal-overlay">
    <div class="forgot-modal-box">

        <!-- Use same close button class -->
        <span class="close-forgot" onclick="closeNewEmailModal()">X</span>

        <h2>New Email</h2>
        <p>Please enter a new email.</p>

        <form id="newEmailForm">

            <label>New Email:</label>
            <input type="password" placeholder="Enter new email" required>

            <label>Confirm New Email:</label>
            <input type="password" placeholder="Confirm new email" required>

            <div class="forgot-btn-row">
                <!-- Use same button styles -->
                <button type="button" class="forgot-send" onclick="submitNewEmail()">Send</button>
                <button type="button" class="forgot-change" onclick="closeNewEmailModal()">Cancel</button>
            </div>
        </form>

    </div>
</div>
<!-- FOOTER BAR BUT only for the login page so idk if we should have a separate file/footer for it -->


<?php if ($show2fa_login): ?>
<div class="twofa-modal-overlay">
  <div class="twofactor-container">
    <span class="close-btn" onclick="close2FAModal()">X</span>

    <h1>Two-Factor Authentication</h1>
    <p>Please enter the 6-digit code sent to your phone.</p>

    <form method="POST" action="<?= APP_BASE_URL ?>/login/2fa">
      <input type="text" name="code" id="code" maxlength="6" placeholder="XXXXXX" required style="color:white;">

      <div>
        <button type="submit" class="verify">Verify</button>
        <button type="button" class="resend" onclick="resend2FACode()">Resend Code</button>
      </div>
    </form>
  </div>
</div>
<?php endif; ?>

<?php
ViewHelper::loadJsScripts();
ViewHelper::loadFooter();
?>

<script>
function close2FAModal() {
  document.querySelector('.twofa-modal-overlay').style.display = 'none';
}

function resend2FACode() {
  // TODO: AJAX request to resend
  alert("Code resent!");
}
</script>
